apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 4567  # Port exposed within the cluster
      targetPort: 4567  # Port your backend listens on
      nodePort: 31000  # Choose a port in the range 30000-32767
