apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend # Match the labels in your Deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000  # Port exposed within the cluster
      targetPort: 3000  # Port container is listening on
      nodePort: 31001
  externalIPs:
   - 192.168.49.2 