apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend  # This label should match the label in the template
  template:
    metadata:
      labels:
        app: frontend  # This label should match the label in the selector
    spec:
      containers:
        - name: frontend
          image: minighazal/frontend:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"  # Minimum memory required
              cpu: "100m"      # Minimum CPU required
            limits:
              memory: "500Mi"  # Maximum memory allowed
              cpu: "500m"      # Maximum CPU allowed
